server:
  port: 8080

spring:
  ai:
    openai:
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0
          top-p: 1
      api-key:
logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.http.client: DEBUG
